# Generated by Django 4.1.4 on 2023-04-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.OneToOneField(default=None, on_delete=models.SET(None), to='main.company'),
        ),
    ]
