# Generated by Django 4.1.4 on 2023-04-18 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_employee_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='company',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.company'),
        ),
    ]
